.DEFAULT_GOAL = run

GENERIC_MAKEFILE = ../../test.makefile

run:
	make -C $(CURDIR) --file=$(GENERIC_MAKEFILE) run

rundrm:
	make -C $(CURDIR) --file=$(GENERIC_MAKEFILE) rundrm

clean:
	make -C $(CURDIR) --file=$(GENERIC_MAKEFILE) clean